rag:
  region: us-east-1
  embedding: 
    embed_endpoint_name: huggingface-textembedding-gpt-j-6b-fp16
  llm:
    llm_endpoint_name: Llama-2-7b-fp16
    parameters: 
      max_new_tokens: 500
      return_full_text: False
      temperature: 0.1
mongo:
  DB_NAME: "langchain_test_db"
  COLLECTION_NAME: "langchain_test_vectorstores"
  ATLAS_VECTOR_SEARCH_INDEX_NAME: "langchain-test-index-vectorstores"
